POST http://localhost:4011/api/phonebill
content-type: application/json

{
    "price_plan" : "sms 101",
    "actions" : "call, sms, call, call, sms"
}

###

POST http://localhost:4011/api/price_plan/create
content-type: application/json

{
    "name" : "call 111",
    "call_cost" : 1.80,
    "sms_cost" : 0.67
}

###
POST http://localhost:4011/api/price_plan/update
content-type: application/json

{
    "name" : "call 111",
    "call_cost" : 3.65,
    "sms_cost" : 1.70
}

###

POST http://localhost:4011/api/price_plan/delete
content-type: application/json

{
    "id" : 5
}

###
GET http://localhost:4011/api/price_plans/

###

GET http://localhost:4011/api/history

